[versions]
log4j = "2.25.3"

[plugins]
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }
versions = { id = "com.github.ben-manes.versions", version = "0.53.0" }

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "26.0.2-1" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version = "6.0.2" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher", version = "6.0.2" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }

[bundles]
